### ISSUE TITLE
Maze generation should produce an intermediate representation- formatting and drawing should be a different executable

### ISSUE THREAD

**Issue by joeatwork** [joeatwork/mazes-c#1]
I'm thinking producing GraphViz DOT output might be the best idea. Mixing the maze generation and image production is a bit ununixy

**Comment by jamis** [comment]
Yes, please! I love the idea of applying the unix philosophy to maze generation.

**Comment by joeatwork** [comment]
WOOOT - lots of little exes producing dot files
